### ISSUE TITLE
Reconsider the use of provenance field

### ISSUE THREAD

**Issue by mjanowiecki** [geoblacklight/geoblacklight#1018]
I know we've discussed how provenance has a different meaning for a lot of LIS folks, and I was wondering if we want to stick with this terminology in general? I have been wandering around linked open data terminologies, and wonder if [provider](https://schema.org/provider) makes more sense?

Looking forward to hearing folks thoughts 😃  Here's the working schema spreadsheet link if needed: [GeoBlacklight metadata analysis](https://docs.google.com/spreadsheets/d/1QQjUzRe8YdPGKK4h0GYoNPTow2zZ1f0KFA0zzZyHAsk/edit#gid=1481740149)

**Comment by karenmajewicz** [comment]
Thoughts on what different things this field could be indicating an organization that:

1. has an archived copy of the resource
2. hosts the server providing web services for data or IIIF (i.e. GeoServer)
3. wrote the metadata from the item
4. processed existing metadata and added it to a local catalog/repository
5. identified an external resource and added it just to GeoBlacklight (see nearly all the GIS data in geo.btaa.org)
6. originally provided/published the resource (see the Held By facet at geodata@wisc.edu)

There are likely other examples as well.  One thing all of these have in common is that I don't see the provenance info as being very helpful for users most of the time. Most of the organizations that participate with GeoBlacklight have added their school icon to the project so that it shows up for users. Can we articulate why this is important?

-----
Since the interpretations of the field vary, I would support the most generalized field name we can come up with.

**Comment by lenathelibrarian** [comment]
Sounds like schema:provider was decided on (woohoo!) but if you need more hands on deck, I'm happy to work on this with you

**Comment by karenmajewicz** [comment]
consensus around schema_provider_s , preferably _sm
