### ISSUE TITLE
Provide a more graceful fallback for non-parsable geometry

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#1042]
### Descriptive summary

Some records may not be parsable by RGeo, and now raise an error. We should do something better so there aren't errors in search results. https://github.com/geoblacklight/geoblacklight/blob/main/lib/geoblacklight/geometry.rb#L20

Downstream issues: https://github.com/sul-dlss/earthworks/issues/778

**Comment by karenmajewicz** [comment]
I just encountered what I think may be a result of this problem. I attempted to index a collection of maps into our development site (newly upgraded to v.3.3). A handful of records caused an error reported as "LinearRing failed ring test". Unfortunately, this meant that any search that included one of those items caused the site to fail.

I discovered that the problem records had coordinates that did not truly form a closed box. In these cases, the E & W OR the N & S coordinates were the same value. In the previous version of GeoBlacklight, these would have shown up on the map as a straight line (not ideal, but didn't break the search page).

I added a fraction of a degree to the E and/or N coordinates for these maps and they indexed just fine after that.

**Comment by dl-maura** [comment]
We've written up a quick record corrector (found here: https://github.com/harvard-lts/gbl_json_fix) that adjusts the coordinates in the geojson field when they match so that they will be slightly adjusted to make a real box. Not a perfect box but seems to do the job for a quick fix for those using 3.3 -- reviewed by @karenmajewicz

**Comment by eliotjordan** [comment]
The underlying issue here, is that the envelopes / bounding boxes should be valid polygons. The most important reason is the enable a valid solr spatial search with the item. Changing the underlying geometry processing, uncovered this metadata problem. Perhaps we should add some validation to the envelope in GeoCombine. That being said, invalid polygon geometry should not crash GeoBlacklight. After doing some experimentation and reading, I've come to understand that this is a bit of a tricky issue. As far as I can tell, the problem is the underlying version of `libgeos`,  which can be different between machines. For example, I can't replicate this directly on my development laptop. Everything works as it should. So it is hard to test. I'll work up a patch that tests the error indirectly and let's see if it fixes the problem.

**Comment by eliotjordan** [comment]
Needs a some more work.

**Comment by karenmajewicz** [comment]
We can leave this issue closed, but I think this will continue to be something that pops up. After going through the BTAA scanned maps records and talking to MARC cataloguers, it appears to be very common to use a point for coordinates. This particularly occurs when they use a service like Klokan or GeoNames. Many cities are presented just as a point in those services, and there are no MARC-related cataloging rules saying that is not acceptable. Exploring a solution similar to Maura's, which programmatically turns a point into a small box might be another option.
