### ISSUE TITLE
Map don't show (docker build)

### ISSUE THREAD

**Issue by Dragonking3x** [geoblacklight/geoblacklight#1242]
### Descriptive summary

We are currently working on a docker version of geoblacklight, and we have some bugs with the website.
After the start, we can't see the map.
![image](https://user-images.githubusercontent.com/16963388/183091217-0be28795-ab1f-4e27-a05d-257824365b76.png)

We are still working on the steps to get the datasets from Dataverse into Geoblacklight.
We have an Issue open about that problem on Geodisy.
https://github.com/ubc-library/geodisy/issues/70

### Expected behavior
Even with no data, it should show the map.

### Actual behavior

Map doesn't work.
Trying to register a user gives an error.

### Steps to reproduce the behavior

1. Download this zip with the docker-compose files
[geoblacklight_docker.zip](https://github.com/geoblacklight/geoblacklight/files/9270264/geoblacklight_docker.zip)

2. Download The geoblacklight zip
https://github.com/geoblacklight/geoblacklight/releases/tag/v3.7.0

3. export both .zip in the same folder
![files_and_folders](https://user-images.githubusercontent.com/16963388/183119593-7fff4d08-e833-49bb-8992-dbaad8841dd2.png)

4. move in the folder and give the folder "volume" permissions
`sudo chmod -R 777 volumes/`

5. start the docker
`docker network create traefik`
`docker-compose up`

6. setup geoserver
http://127.0.0.1:8600/geoserver/
user: admin
password: testpassword
![geoserver_workspace](https://user-images.githubusercontent.com/16963388/183119663-05b49c65-a6de-45ba-9d5e-eead2e509627.png)
![geoserver_storage_1](https://user-images.githubusercontent.com/16963388/183119675-37741b78-1786-4a52-b410-0248a2f0b84a.png)
![geoserver_storage_2](https://user-images.githubusercontent.com/16963388/183119755-52d3f3d0-8375-426b-b800-9b1608f5069e.png)

7. setup database
`docker exec geoblacklight_v2c2_dataverse rails db:migrate`

8. restart docker-copose (if it doesn't work)
ctrl+c
`docker-compose up`

9. open geoblacklight
http://127.0.0.1:3000

**Comment by dl-maura** [comment]
@Dragonking3x Do you have the dockerfile and docker-compose available in GitHub?

**Comment by ewlarson** [comment]
Hi @Dragonking3x

Sorry for the trouble, but I am not able to recreate this issue running GBL v3.7.0 locally. I spun up your docker implementation and it's just not loading GBL's Javascript classes at all (Geoblacklight.Viewer, etc.), so that's why the map is not rendering.

I'm closing this issue, as it's not an error in the GBL codebase, but rather some challenge to solve in your implementation.

<img width="998" alt="Screen Shot 2022-08-08 at 2 44 01 PM" src="https://user-images.githubusercontent.com/69827/183501995-d8f61aa2-3160-4d7b-845e-8c4876aa48bf.png">
