### ISSUE TITLE
JavaScript testing preferences?

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#322]
I'm looking into adding JavaScript tests to GeoBlacklight using [Teaspoon](https://github.com/modeset/teaspoon). Does anyone have strong feelings about this (pro or con)? Any strong feelings on Mocha vs. Jasmine?

https://github.com/modeset/teaspoon/wiki/Testing-Engine-Assets

**Comment by eliotjordan** [comment]
No strong opinions, but Mocha has nice features and is, I believe, used in Leaflet tests.

**Comment by eliotjordan** [comment]
Hi everyone. Bumping this thread because I'd like to possibly incorporate JS tests into the new ESRI module. @mejackreed has a PR #338 around this topic. Does anyone have personal experience with JS testing? Thoughts... @drh-stanford @gravesm

For reference: http://thejsguy.com/2015/01/12/jasmine-vs-mocha-chai-and-sinon.html

**Comment by gravesm** [comment]
I've used jasmine quite a bit and like it, but I don't have any problems using something else.
