### ISSUE TITLE
Gather use cases for index maps

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#459]
Types of data:
- historic maps
- imagery?

What type of data are needed as attributes?
- urls to the image access point?
- iiif?
- thumbnails?

Support a grid only? Support center points?

Support for custom institution specific fields? 
- barcode?

All of this needs to be fleshed out a bit more before we move forward with developing #406

**Comment by andrewbattista** [comment]
Chiming in here. I like the ideas on this thread and the ones on #406 as well. From what I can tell, this feature would mostly meet specific collection development contexts, such as the ones mentioned (adding a bunch of sheets from a given series). I think one way that @sgbalogh and I had envisioned this was to use the parent-child convention with the data relations and mark these connections that way. 

But this is a good method, and I like the idea of using the example you've provided as a template. I don't see a problem with creating a standard shapefile layer so that others can replicate.

As for data in the attribute table, my preference is to link to the GeoBlacklight layer record for each individual map, as Darren has mocked up.

**Comment by andrewbattista** [comment]
For the purposes of our upcoming sprint, is it OK to close this issue and assume that the essence of it is merged with #406 ?
