### ISSUE TITLE
More info for search results is double escaped

### ISSUE THREAD

**Issue by gravesm** [geoblacklight/geoblacklight#493]
The more info part of a search result is double escaped:

![document](https://cloud.githubusercontent.com/assets/1382348/17702842/9c7360ec-639d-11e6-8edc-e36a05f71cb9.jpg)

This content has already passed through `ERB::Utils.html_escape` in Blacklight and then gets escaped again by Rails by default. We should either not explicitly escape it and let Rails handle it or mark it as safe in the template.

**Comment by dmolesUC3** [comment]
Rather than in the template (which apparently is considered bad practice), it could be marked `html_safe` in [Geoblacklight::DocumentPresenter](https://github.com/geoblacklight/geoblacklight/blob/v1.3.0/app/presenters/geoblacklight/document_presenter.rb). (Or possibly kicked upstream to [Blacklight::FieldPresenter](https://github.com/projectblacklight/blacklight/blob/dee8d794125306ec8d4ab834a6a45bcf9671c791/app/presenters/blacklight/field_presenter.rb).)

**Comment by andrewbattista** [comment]
I'm almost positive that this issue has already been addressed. Can someone confirm, and if so, we can close this issue?
