### ISSUE TITLE
Remove hardcoded field name

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#514]
`layer_slug_s` https://github.com/geoblacklight/geoblacklight/blob/master/lib/geoblacklight/relation/ancestors.rb#L10-L11

**Comment by cueBall123** [comment]
Hi,
Can I help to fix this?

**Comment by andrewbattista** [comment]
Eliot and I worked on this for a couple afternoons, and after much testing and investigation, we discovered this:

We can't make [this line](https://github.com/geoblacklight/geoblacklight/blob/fcb08e1a7f205a5d90272e83bb98833bbacf2a32/lib/generators/geoblacklight/install_generator.rb#L62) configurable because the install generator can't read the settings file. Because of this, unique keys can't be configurable.

We recommend that we let this one slide and close the issue. What's done is done.

**Comment by andrewbattista** [comment]
Forgot this @mejackreed can you look at this and confirm?
