### ISSUE TITLE
add support for geometry-based (i.e., polygon) bounding regions

### ISSUE THREAD

**Issue by drh-stanford** [geoblacklight/geoblacklight#524]
Currently in 1.x GeoBlacklight only supports rectangular bounding boxes

**Comment by mejackreed** [comment]
For searching, display (preview) or both?

**Comment by drh-stanford** [comment]
more for display/preview, but maybe the API could search by polygon too

**Comment by sgbalogh** [comment]
Was just talking about this with @eliotjordan actually –– it could be useful if the solr_geom for a record could more precisely reflect the physical geometry of the location by using a polygon, even if the search interface still issued rectangular search queries. It would fix the problem of, for instance, getting hits for USA records while looking at regions off the coast/across the border that still fall inside a bounding box of the USA (as is the case with large amounts of Canada or Mexico, etc.).

**Comment by mejackreed** [comment]
Yep this would be great, but would complicate Solr setup as it would force users to manually install JTS.

**Comment by sgbalogh** [comment]
Ahh, good point. Do you think that would be sufficiently annoying to justify leaving this out?

Just thinking out loud... another way to not cut users who do not have the ability to add JTS to their Solr env and still allow them to use shared OGM metadata with complex geoms would be to add a function in GeoCombine to extract rectangular bounding boxes and index those simple geoms instead. That would probably force a related (but perhaps smaller?) issue of requiring people to install GDAL...

**Comment by mejackreed** [comment]
I think if we added smarter parsing of the geometry (like [blacklight-heatmaps](https://github.com/sul-dlss/blacklight_heatmaps/blob/master/app/models/concerns/blacklight_heatmaps/geometry_parser.rb) does) we could do this without having to add the solr requirement

**Comment by sgbalogh** [comment]
Hm, not sure I understand. Isn't the above just code for parsing geo objects from different representations of them?

**Comment by mejackreed** [comment]
Yep, so if we know how to parse things in a smart way.. we can index that field as anything SRPT https://cwiki.apache.org/confluence/display/solr/Spatial+Search#SpatialSearch-RPT . And people can index whatever they want. (they already can ... its just not really supported in the software at the moment)

**Comment by sgbalogh** [comment]
Oh, right. But it would still be the case that if NYU is publishing records with complex polygon geoms and someone without JTS wanted to index our records, they wouldn't be able to. Thats what I was suggesting with a geometry simplifier component of GeoCombine, just as a way to make all records "backwards compatible" if we did this

But agreed that the blacklight-heatmaps way is a smart way of supporting different formats of geom once they are in a record

**Comment by mejackreed** [comment]
Ah yeah I get what you mean.. +1

**Comment by sgbalogh** [comment]
Experimenting with this a bit at the moment. One solution seems to be to replace the solr_document method `bounding_box_to_wsen` with something more similar to the code from blacklight-maps linked above, and have a function that takes either WKT or solr ENVELOPE syntax shapes and produces a GeoJSON string (which is what will then go into the relevant data attribute of the map divs). GeoJSON is necessary for polygons that are more complicated than a rectangle (because WKT is not understood by Leaflet). I'm using a GeoRuby (https://github.com/nofxx/georuby) function to do the WKT -> GeoJSON conversion. Then I just change the Leaflet JS functions such that they expect a L.geoJson object instead of a simple bbox.

Seems to be working well so far... haven't needed to modify anything with the search builder. Any thoughts about this direction?

![geom](https://cloud.githubusercontent.com/assets/10469527/22751217/a4296e14-ee01-11e6-84f5-e7af1c72b748.gif)
