### ISSUE TITLE
Add text search within the map/spatial search

### ISSUE THREAD

**Issue by MetaMara** [geoblacklight/geoblacklight#528]
### Descriptive summary

Adding a text box to the map search that would allow users to search text/place name would increase the utility of the spatial search. It is difficult to pan and zoom to a place if you do not know exactly where it is.

**Comment by eliotjordan** [comment]
Add documentation on wiki page on how to customize leaflet.

**Comment by jrgriffiniii** [comment]
I'm progressing towards extending the existing documentation by providing the following:

# Plugins for Leaflet
Customizing Leaflet has certain limitations which can fortunately be overcome through the usage of plugins developed by third parties.  Leaflet provides the following listing of plugins for the library: https://leafletjs.com/plugins.html#search--popups.

## Downloading Leaflet Plugins
Firstly, in order to integrate a plugin, the JavaScript source file(s) are downloaded into the `vendor/assets/javascripts` directory, where names are all in the lower case, with whitespace being replaced by dash characters (e. g. `vendor/assets/javascripts/esri-leaflet.js`

## Integrating Plugins into Leaflet
Integrating a plugin varies depending upon precisely what is being used, but the general approach seems to often follow a pattern such as the following:
```
var searchLayer = L.layerGroup().addTo(map);
//... adding data in searchLayer ...
map.addControl( new L.Control.Search({layer: searchLayer}) );
```
...where an `L.Control` has `addTo` invoked using the `map` Object as an argument.  Using another example:
```
new L.Control.GPlaceAutocomplete({
	callback: function(place){
		var loc = place.geometry.location;
		map.setView( [loc.lat(), loc.lng()], 18);
	}
}).addTo(map);
```


## Integrating Plugins into Leaflet using GeoBlacklight
When integrating this GeoBlacklight, the approach above could modified by extending the previous example:

```
...
  VIEWERS:
      WMS:
        CONTROLS:
          - 'Opacity'
          - 'Fullscreen'
          - 'Search'
...
```

```
// In your applications's app/assets/javascripts/geoblacklight.js
...
//= require 
//= require leaflet-search


GeoBlacklight.Controls.Search = function() {
  this.map.addControl(new L.control.search({
    geocoder: 'google'
  }));
};

```

**Comment by eliotjordan** [comment]
Are these proposed changes for https://github.com/geoblacklight/geoblacklight/wiki/Adding-Leaflet-control-customization-to-GeoBlacklight ?

**Comment by jrgriffiniii** [comment]
I'm sorry @eliotjordan, they are indeed.  I could also restructure these for a separate page on the Wiki.

**Comment by jrgriffiniii** [comment]
This has been added to https://github.com/geoblacklight/geoblacklight/wiki/Adding-Leaflet-control-customization-to-GeoBlacklight
