### ISSUE TITLE
Gracefully handle metadata viewing when metadata is not accessible

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#559]
### Descriptive summary

When viewing metadata, if it is unavailable, it basically just shows a large blank page

<img width="1200" alt="screen shot 2017-08-03 at 8 26 38 am" src="https://user-images.githubusercontent.com/1656824/28929690-83b573e0-7825-11e7-9218-11f7727ad6df.png">

### Expected behavior
Some more graceful, perhaps a message to the user, and a smaller page?
### Steps to reproduce the behavior
In demo data, view: http://127.0.0.1:3000/catalog/08329e96-3779-4cea-9fa8-5d9939b6276f

The metadata at https://opengeometadata.github.io/edu.umn/08/32/9e/9637794cea9fa85d9939b6276f/iso19139.xml 404's

### Related work
HTML view of metadata implemented here: https://github.com/geoblacklight/geoblacklight/pull/555

**Comment by ewlarson** [comment]
I'll toss another wrench in here... We have a little over 500 docs/items in our geoportal from the [Minnesota Geospatial Commons](https://gisdata.mn.gov/) where the associated metadata is made available via FTP and not HTTP.  Since Geoblacklight::Metadata::Base.retrieve_metadata uses Faraday (HTTP only), these records toss a 500 error upon requesting the metadata via its [FTP address](ftp://ftp.gisdata.mn.gov/pub/gdrs/data/pub/edu_umn/base_historical_aerial_points/metadata/metadata.xml).

I can see a solution forking the retrieve_metadata function's logic using URI.parse('ftp://foo...').scheme to route FTP versus HTTP requests... but maybe this is uniquely a B1G Geoportal problem?  Any thoughts @jrgriffiniii on how we might handle this problem?

**Comment by jrgriffiniii** [comment]
@ewlarson I'm very sorry for the delay in investigating this, I can look towards deprecating Faraday and extending handling for FTP support.
