### ISSUE TITLE
Download panel refactoring

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#607]
Open up the download panel so it is more configurable for different types of download presentations.

Inspired by Cornell's change to the download panel.

**Comment by jrgriffiniii** [comment]
This should also take into account the deprecation of certain UI components in the future upgrade to Bootstrap 4.

**Comment by jrgriffiniii** [comment]
Usability concerns have been raised regarding the disambiguation of the generation (and caching) of secondary downloads and the downloading of primary files linked to a Document (e. g. users must click twice in order to download certain files, the "Download" button is not disabled once it has been clicked for generated files, and other cases...)  I will take this into account in my progress on this.

**Comment by jrgriffiniii** [comment]
Currently I've taken an approach in which I've removed the "Downloads" from the "Tools" template partial, and further restructured these in order to distinguish between secondary (generated/cached) downloads, and primary downloads:

<img width="1292" alt="geoblacklight_issues_607_screenshot_0" src="https://user-images.githubusercontent.com/1443986/43165663-7d1d14e8-8f62-11e8-80e6-8cdb36778a38.png">

Currently my work is on https://github.com/geoblacklight/geoblacklight/compare/master...jrgriffiniii:issues-607-jrgriffiniii-dl-panel-refactor, but I felt it best to request some feedback from @eliotjordan @ewlarson @KarenMajewicz @mejackreed and any other interested parties before finalizing this for a Pull Request.

**Comment by KarenMajewicz** [comment]
I like this direction.  I assume it is the same for IIIF?

I wonder if the panel titles could be more explicit?  What's the pithiest way of saying: "Dynamically generate a download from this item's web service?"  

I have to wonder how many actually users understand the difference here?  For example, the original file may have a different projection or resolution than the generated file; does this need to be clarified for the user anywhere?  

I also took a look at how Socrata data portals handle this.  All the downloads are together in the same panel, but one is called "Original." Originals in Socrata for GIS data seem to be only Shapefiles or KMZ and you have to download it to find out. ([Link to example](https://data.cityofchicago.org/Facilities-Geographic-Boundaries/Boundaries-ZIP-Codes/gdcf-axmw), need to click Export). Maybe we could use a phrase like "Original {format}"?  

![socrataex](https://user-images.githubusercontent.com/2367677/43166804-3a92418e-8f5d-11e8-9658-11bb29bca567.png)

**Comment by jrgriffiniii** [comment]
@KarenMajewicz Thank you for the feedback and guidance.  I have incorporated some of these changes, and have attempted to make the overall styling more consistent:

![geoblacklight_issues_607_screenshot_1](https://user-images.githubusercontent.com/1443986/43208516-a0210d3c-8ff8-11e8-815a-6140d2263fbe.png)

If this is satisfactory, I need to refactor a bit further and improve the JavaScript a bit.

**Comment by mapninja** [comment]
I think this is a marked improvement. more intuitive and informative, as well as reducing clicks.
