### ISSUE TITLE
Add support for GeoPackage

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#608]
It might be a good idea to add first class support for GeoPackage

**Comment by jrgriffiniii** [comment]
For the purposes of documentation, is this considered to be both Vector or Raster in all cases?  Raster tile grids are supported according to the documentation: 
>The GeoPackage Tiles option specifies a mechanism for storing raster data in tile pyramids. “Tile pyramid” refers to the concept of pyramid structure of tiles of different spatial extent and resolution at different zoom levels, and the tile data itself. “Tile” refers to an individual raster image such as a PNG or JPEG that covers a specific geographic area. “Tile matrix” refers to rows and columns of tiles that all have the same spatial extent and resolution at a particular zoom level. “Tile matrix set” refers to the definition of a tile pyramid’s tiling structure. This mechanism is based on the model for tile matrix sets described in Section 6 of the WMTS Implementation Specification.

(http://www.geopackage.org/guidance/getting-started.html)

GeoServer seems to support both as well: 
> GeoPackage is an SQLite based standard format that is able to hold multiple vector and raster data layers in a single file.
>
> GeoPackage files can be used both as Raster Data Stores as well as Vector Data Stores (so that both kinds of layers can published).

(http://docs.geoserver.org/stable/en/user/data/vector/geopkg.html)

**Comment by jrgriffiniii** [comment]
If the assumption is that these would be exposed using WMS/WFS endpoints, then I'm not certain how to proceed beyond improving documentation.  I am sorry if I am misunderstanding this.

I have modified the schema `dc_format_s` for "GeoPackage" as a valid format value:
https://github.com/geoblacklight/geoblacklight/compare/master...jrgriffiniii:issues-608-jrgriffiniii-geopackage?expand=1

My understanding of the JSON schema is that this cannot be enforced because it is optional:
https://github.com/geoblacklight/geoblacklight/blob/master/schema/geoblacklight-schema.json#L112

I have also added this to the Wiki: https://github.com/geoblacklight/geoblacklight/wiki

Should any updates be made to https://github.com/OpenGeoMetadata/GeoCombine in an attempt to extract vector/tile bounding box extents?

**Comment by jrgriffiniii** [comment]
After discussing this with @andrewbattista, @ewlarson, and @eliotjordan, this issue is also related to cases in which multiple downloads for data sets should be supported (https://github.com/geoblacklight/geoblacklight/issues/340).

Further, concerns focused upon the extraction of feature attributes from GeoPackage databases were raised (particularly as to whether or not these types of queries would be supported as they are with Shapefiles or GeoTIFFs).

**Comment by jrgriffiniii** [comment]
Unfortunately, it also does not seem to be the case that GeoPackage validation in Ruby is offered by any libraries supported by the [National Geospatial-Intelligence Agency](http://ngageoint.github.io/GeoPackage/)

**Comment by jrgriffiniii** [comment]
I propose adding the following documentation on the Wiki:
```
[GeoPackage](http://www.geopackage.org/) is an encoding standard specified and maintained by the [Open Geospatial Consortium](http://www.opengeospatial.org/), primarily directed towards the structure of SQLite geodatabases.  As the GeoPackage standard provides standardization for vector features, tile matrix sets, and raster maps, it may be used as a container for either [vector or raster spatial data sets](https://www.ordnancesurvey.co.uk/support/understanding-gis/raster-vector.html).

Librarians or curators are responsible for the data imported into GeoBlacklight, and as such, this application  cannot disambiguate between GeoPackages and other (non-compliant) SQLite geodatabases.  The [GeoBlacklight schema](https://github.com/geoblacklight/geoblacklight/blob/master/schema/geoblacklight-schema.md#format) does provide one with the ability to provide a “GeoPackage” value to the `dc_format_s` field.

GeoPackages may be rendered using the layer viewer by providing the URL of a standard Web Map Service ([WMS](http://www.opengeospatial.org/standards/wms)) or Web Feature Service ([WFS](http://www.opengeospatial.org/standards/wfs)) within the `dct_references_s` field of [the schema](https://github.com/geoblacklight/geoblacklight/blob/master/schema/geoblacklight-schema.md#format).  For those who are currently using GeoServer in order to provide access to these data sets, the documentation outlines the process for uploading data sets and extracting [vector](http://docs.geoserver.org/latest/en/user/data/vector/geopkg.html) or [raster](http://docs.geoserver.org/latest/en/user/data/raster/geopkg.html) layers.  Further, there also exists a [plugin](http://docs.geoserver.org/latest/en/user/community/geopkg/) which permits one to export vector or raster data layers into GeoPackages (please see [further documentation outlining the extended WMS/WFS output formats](http://docs.geoserver.org/stable/en/user/community/geopkg/output.html)).
```

Unfortunately (as stated above), exporting into GeoPackage in GeoServer requires that one install a plugin.  Only reading is supported by GeoServer core.

**Comment by jrgriffiniii** [comment]
The proposed documentation has been added to the Wiki: https://github.com/geoblacklight/geoblacklight/wiki
