### ISSUE TITLE
Bounding Boxes crossing the 180th meridian display horizontally flipped

### ISSUE THREAD

**Issue by karenmajewicz** [geoblacklight/geoblacklight#616]
### Descriptive summary

When the bounding box straddles the 180th meridian, the search results will show the footprint incorrectly. This is a known bug, but perhaps we can address or at least document it to warn people of the behavior.

Examples:
https://geo.btaa.org/?utf8=%E2%9C%93&f%5Bdct_isPartOf_sm%5D%5B%5D=John+R.+Borchert+Map+Library&per_page=20&search_field=all_fields&q=ortelius

https://maps.princeton.edu/?utf8=%E2%9C%93&featured=scanned_maps&search_field=all_fields&q=East+Asia+and+Oceania
  

### Related work

VecNet issues:
https://github.com/vecnet/dl-discovery/issues/12
https://github.com/vecnet/dl-discovery/issues/61

Big 10 issue:
https://github.com/BTAA-Geospatial-Data-Project/geoportal/issues/84

**Comment by mejackreed** [comment]
Can you confirm that the data `ENVELOPE(35.33203125, -170.859375, 81.1744910043, -6.1405547825)` is correct here for that data?

The CQL Envelope syntax requires `ENVELOPE(#{west}, #{east}, #{north}, #{south})` so I'm reading that as the `WEST` or minimum longitude is larger than the maximum longitude so I think it might be a malformed bounding box rather than a bug in the code. 

I'm typing all of this out because the CQL syntax always confuses me. If the bounding box is updated, does it get the correct functionality in GeoBlacklight?

**Comment by mejackreed** [comment]
Gah.. now I see what you mean! 

Looks like we need to be a bit more clever with how we pass things to Leaflet:

> Caution: if the area crosses the antimeridian (often confused with the International Date Line), you must specify corners outside the [-180, 180] degrees longitude range. Note that LatLngBounds does not inherit from Leafet's Class object, which means new classes can't inherit from it, and new methods can't be added to it with the include function.

 - http://leafletjs.com/reference-1.3.0.html

**Comment by KarenMajewicz** [comment]
(Yes, this issue has been tricky to troubleshoot, because sometimes the coordinate order in the metadata record has been entered incorrectly.) One bounding box that I have found a little easier to envision for this problem is for the state of Alaska.  Klokan Bounding Box provides the bounding coordinates for Alaska as: westlimit=172.3; southlimit=51.2; eastlimit=-130.0; northlimit=71.4.  Here are some good examples from Earthworks: https://earthworks.stanford.edu/?f%5Bdct_provenance_s%5D%5B%5D=Stanford&q=alaska

**Comment by christinach** [comment]
I worked on this issue in 2018. I'm adding the old work for reference for anyone who would like to work on this https://github.com/geoblacklight/geoblacklight/pull/682
