### ISSUE TITLE
Show page tool bar formatting

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#641]
- Tool items have borders
- Empty tools display as items

![screenshot 2018-07-25 18 31 31](https://user-images.githubusercontent.com/784196/43232984-486c4e80-9039-11e8-979c-f43aaeb4f7bd.png)

![screenshot 2018-07-25 18 51 38](https://user-images.githubusercontent.com/784196/43233498-d39be2d4-903b-11e8-93c7-daa22906302e.png)

Versus...

![screenshot 2018-07-25 18 31 37](https://user-images.githubusercontent.com/784196/43232986-4de29568-9039-11e8-8493-02fcab3e9bcf.png)

**Comment by jrgriffiniii** [comment]
I'm finishing an attempt at slightly redesigning this:

<img width="558" alt="geoblacklight_issues_641_screenshot_0" src="https://user-images.githubusercontent.com/1443986/43332682-dfa7809a-9196-11e8-831c-38ebb6b0a239.png">

I'm deviating from the original design in order to preserve the font size (for a11y purposes).  Please note that I will need to change the authentication text:

<img width="371" alt="geoblacklight_issues_641_screenshot_1" src="https://user-images.githubusercontent.com/1443986/43332778-2962fd36-9197-11e8-9588-a428e2d67d60.png">
