### ISSUE TITLE
FeatureLayer - Empty JSON request results

### ISSUE THREAD

**Issue by ewlarson** [geoblacklight/geoblacklight#717]
### Descriptive summary

GeoBlacklight 1.9+ exhibits an error, similar to #715, where click events and API query calls for FeatureLayer points and polygons return no feature results.

### Expected behavior

Expect to remotely fetch feature click data successfully.

### Actual behavior

Many requests are returning zero results.

### Steps to reproduce the behavior

1. Checkout master
2. bundle exec rake geoblacklight:server
3. Visit http://localhost:3000/catalog/f406332e63eb4478a9560ad86ae90327_18
4. No markers will present. Move your mouse across the map and you'll see it turn into a pointer. Try clicking that area.

You'll see a console error "Cannot read property 'properties' of undefined". If you look at your XHR requests, you'll see [this json request](https://geodata.md.gov/imap/rest/services/Transportation/MD_Transit/FeatureServer/18/query?returnGeometry=false&where=1%3D1&outSr=4326&outFields=*&inSr=4326&geometry=%7B%22x%22%3A-76.932817%2C%22y%22%3A38.748261%2C%22spatialReference%22%3A%7B%22wkid%22%3A4326%7D%7D&geometryType=esriGeometryPoint&spatialRel=esriSpatialRelIntersects&f=geojson) was made.

### Related work

This issue is undoubtedly related to our recent GBL 1.9 leaflet and esri-leaflet updates:
#679

This issue is also similar to #715

**Comment by jgravois** [comment]
this is happening because the spatial query you are executing looks for other points that intersect the point you are passing in the request.

you have two options:
1. any time you're hitting a modern ArcGIS Server instance like this you can use [`Query.nearby()`](https://esri.github.io/esri-leaflet/api-reference/tasks/query.html#methods) to have the server buffer the input geometry. this will result in a query request that appends [`...&distance=100&units=esriSRUnit_Meter`](https://geodata.md.gov/imap/rest/services/Transportation/MD_Transit/FeatureServer/18/query?where=1%3D1&objectIds=&time=&geometry=%7B%22x%22%3A-76.932817%2C%22y%22%3A38.748261%2C%22spatialReference%22%3A%7B%22wkid%22%3A4326%7D%7D&geometryType=esriGeometryPoint&inSR=4326&spatialRel=esriSpatialRelIntersects&distance=100&units=esriSRUnit_Meter&relationParam=&outFields=*&returnGeometry=false&maxAllowableOffset=&geometryPrecision=&outSR=4326&gdbVersion=&historicMoment=&returnDistinctValues=false&returnIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&multipatchOption=xyFootprint&resultOffset=&resultRecordCount=&returnTrueCurves=false&sqlFormat=none&f=geojson) to what you already shared.

2. if you need to execute a similar query against a very old version of ArcGIS Server, you could use something like turf (or terraformer) to buffer your input geometry clientside.

i hope that helps. if you still have questions, just point me at the code you're using to set up the query i can try and help in a less _theoretical_ way.
