### ISSUE TITLE
More Details translation is missing in show page

### ISSUE THREAD

**Issue by christinach** [geoblacklight/geoblacklight#736]
![screen shot 2019-01-23 at 5 20 53 pm](https://user-images.githubusercontent.com/9905193/51641087-4e5cab80-1f33-11e9-8162-761e54e71fca.png)

**Comment by christinach** [comment]
While debugging this issue after the generator creates the internal_test_app, the specific field: dct_references_s is nil
```
dct_references_s"=>#<Blacklight::Configuration::ShowField label="translation missing: en.geoblacklight.metadata.more_details", accessor=[:external_url], if=#<Proc:0x00007fc220999ed8@/Users/chortariac/apps_team/geoblacklight/.internal_test_app/app/controllers/catalog_controller.rb:141>, helper_method=:render_references_url, key="dct_references_s", field=nil, unless=false>
```
If I save the `geoblacklight/config/locales/geoblacklight.en.yml` without making any change in the file and refresh the page the field to render, changes to the expected one: 
```
"dct_references_s"=>#<Blacklight::Configuration::ShowField label="translation missing: en.geoblacklight.metadata.more_details", accessor=[:external_url], if=#<Proc:0x00007fc1482ac180@/Users/chortariac/apps_team/geoblacklight/.internal_test_app/app/controllers/catalog_controller.rb:141>, helper_method=:render_references_url, key="dct_references_s", field="dct_references_s", unless=false>
```

**Comment by christinach** [comment]
I updated the install_generator.rb to copy the geoblacklight.en.yml in the locales but the filed is still nil.

**Comment by ewlarson** [comment]
Okok... Turns out our "More details at" field label is the only one using I18n in the catalog_controller. All of the other labels within that file are just written directly into it: "Author(s)", "Description", etc.

In [Blacklight](https://github.com/projectblacklight/blacklight/blob/master/lib/generators/blacklight/templates/catalog_controller.rb) and [GeoBlacklight](https://github.com/geoblacklight/geoblacklight/blob/master/lib/generators/geoblacklight/templates/catalog_controller.rb) catalog_controller.rb files I18n translations are not used at all.

This is probably why. Somehow loading the BL config doesn't load locales?

**Comment by christinach** [comment]
Thanks @ewlarson !
