### ISSUE TITLE
Support ISO reference keys with and without a slash

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#809]
Support ISO metadata reference keys with and without a slash:

https://github.com/geoblacklight/geoblacklight/blob/master/lib/geoblacklight/constants.rb#L11

`http://www.isotc211.org/schemas/2005/gmd/`

and

`http://www.isotc211.org/schemas/2005/gmd`

**Comment by ewlarson** [comment]
How does this manifest as a bug? Is there a page or feature that breaks?

**Comment by karenmajewicz** [comment]
It's not exactly a bug - just an inconsistency in our schema. 

Since the ISO reference key is the only one that requires a trailing slash, it would be nice to make it consistent with the others. Instead of making everyone remediate existing metadata, we could just make the trailing slash optional. That way, people going forward could leave it out.

**Comment by christinach** [comment]
It seems that the url for ISO 19139 has changed to https://www.isotc211.org/2005/gmd/
In the code base we have https://github.com/geoblacklight/geoblacklight/blob/f9f1cd4b13f0cc1344230d8d3b7efb2a489714f2/lib/geoblacklight/constants.rb#L11

**Comment by andrewbattista** [comment]
@christinach right, but I think the initial discussion is, should we take out the slash now so that all the URI strings function the same way? The larger goal should be to make GBL smart enough to recognize either. It seems like the fix for that to happen would have to be done here? https://github.com/geoblacklight/geoblacklight/blob/f9f1cd4b13f0cc1344230d8d3b7efb2a489714f2/lib/geoblacklight/metadata/base.rb 

Not sure though...

**Comment by christinach** [comment]
@andrewbattista I've added a fix. I came across the url while I was checking https://www.isotc211.org and wanted to let everyone know that the url we have in the constants it's not valid.

**Comment by christinach** [comment]
It's a different discussion if we want to update it.
