### ISSUE TITLE
Consider a provenance label change for institutions named for a place

### ISSUE THREAD

**Issue by karenmajewicz** [geoblacklight/geoblacklight#933]
### Descriptive summary
During the summer code sprint, I'd like to look into changing the provenance labels for the B1G institutions in the GeoBlacklight codebase. An example would be to change something like "Michigan" to "University of Michigan".

### Background

The provenance field is populated with text strings that are generally short names for institutions. This seems to work fine for named institutions, i.e. Stanford, Purdue, etc.

Following this convention, when the B1G joined, we also used short names. Most of our schools are named after a state or city. Example - for the University of Minnesota, we use "Minnesota". For, the University of Chicago, we use "Chicago." And so on.

However, it may have not been a good decision, because our users are regularly confused by the difference between place name keywords and provenance. So, in addition to changing the labels for the B1G schools, we could also add to the documentation recommendations on how to choose labels in the future.

**Comment by eliotjordan** [comment]
This seems like a good issue to tackle during the upcoming sprint.

**Comment by Wiscmapper** [comment]
I think those changes make sense.  But I also want to put in a plug to make sure that arbitrary text can continue to be used in the provenance field.  We use provenance to indicate who holds the data, which is often times not "Wisconsin."  Could be a state agency, county government, etc.  I know icons on the results page are hard-coded to the various institutions.  We've opted to remove the icon entirely from our custom results pages, since we didn't want to mess with creating icons for every potential "provenance" of data.

**Comment by karenmajewicz** [comment]
[Here is a list of what the institutions in the Big Ten plan to start using.](https://docs.google.com/spreadsheets/d/1g8tyIelphWHjWm8ncVBdsIRbxDApBLPEClPzwJyFIAY/edit?usp=sharing) 

I agree that this would be a good issue for a newer contributor to work on.

**Comment by karenmajewicz** [comment]
I am working on this locally for the B1G instance first.
